{% set name = "ldrb" %}
{% set version = "0.1.1" %}
{% set sha256="f315d41c6181011cb3657a3b1360303372481da163234d4335e679d00ed58ee5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/finsberg/ldrb/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install
  noarch: python

requirements:
  build:
    - python 3.6
  run:
    - python>3.5
    - h5py>=2.8.0
    - sympy 1.1.1
    - fenics 2017.*
    - mshr 2017.*
    - quaternion
    - numpy

test:
  imports:
    - ldrb

about:
  home: https://ldrb.readthedocs.io/en/latest/
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'A software for assigning myocardial fiber orientations based on the Laplace Dirichlet Ruled-Based algorithm'

  description: |
    A software for assigning myocardial fiber orientations based on the Laplace Dirichlet Ruled-Based algorithm.
  doc_url: https://ldrb.readthedocs.io/en/latest/
  dev_url: https://github.com/finsberg/ldrb
