name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["finsberg/fenics", "quay.io/dolfinadjoint/pyadjoint:latest"]

    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/instant
            ~/.cache/dijitso
            ~/.cache/pip
          key: ${{ matrix.container }}-cache_v2
          restore-keys: |
            ${{ matrix.container }}-cache_v2

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install h5py --no-binary=h5py
          python3 -m pip install -e ".[test]"

      - name: Test with pytest
        run: |
          python3 -m pytest
